# Generated by Django 4.1.3 on 2022-11-22 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=200)),
                ('car_model', models.CharField(max_length=50)),
                ('car_condition', models.CharField(max_length=200)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.stream')),
            ],
        ),
    ]
