# Generated by Django 4.1.3 on 2022-11-22 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_rename_stream_manufacturer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='car_name',
        ),
    ]
