# Generated by Django 4.1.3 on 2022-11-22 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_rename_car_name_manufacturer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manufacturer',
            old_name='name',
            new_name='Manufacturer_name',
        ),
    ]
