# Generated by Django 4.1.3 on 2022-11-22 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_rename_name_manufacturer_manufacturer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manufacturer',
            old_name='Manufacturer_name',
            new_name='name',
        ),
    ]
